/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCommentsIndexRouteImport } from './routes/_authenticated/comments/index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts/index'
import { Route as AuthenticatedCountriesIndexRouteImport } from './routes/_authenticated/countries/index'
import { Route as AuthenticatedEpisodesIndexRouteImport } from './routes/_authenticated/episodes/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedFactorsIndexRouteImport } from './routes/_authenticated/factors/index'
import { Route as AuthenticatedGenresIndexRouteImport } from './routes/_authenticated/genres/index'
import { Route as AuthenticatedHeaderMenusIndexRouteImport } from './routes/_authenticated/header-menus/index'
import { Route as AuthenticatedLanguagesIndexRouteImport } from './routes/_authenticated/languages/index'
import { Route as AuthenticatedMoviesIndexRouteImport } from './routes/_authenticated/movies/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedSeasonsIndexRouteImport } from './routes/_authenticated/seasons/index'
import { Route as AuthenticatedSectionsIndexRouteImport } from './routes/_authenticated/sections/index'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommentsIndexRoute =
  AuthenticatedCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCountriesIndexRoute =
  AuthenticatedCountriesIndexRouteImport.update({
    id: '/countries/',
    path: '/countries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEpisodesIndexRoute =
  AuthenticatedEpisodesIndexRouteImport.update({
    id: '/episodes/',
    path: '/episodes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFactorsIndexRoute =
  AuthenticatedFactorsIndexRouteImport.update({
    id: '/factors/',
    path: '/factors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenresIndexRoute =
  AuthenticatedGenresIndexRouteImport.update({
    id: '/genres/',
    path: '/genres/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHeaderMenusIndexRoute =
  AuthenticatedHeaderMenusIndexRouteImport.update({
    id: '/header-menus/',
    path: '/header-menus/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLanguagesIndexRoute =
  AuthenticatedLanguagesIndexRouteImport.update({
    id: '/languages/',
    path: '/languages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMoviesIndexRoute =
  AuthenticatedMoviesIndexRouteImport.update({
    id: '/movies/',
    path: '/movies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeasonsIndexRoute =
  AuthenticatedSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSectionsIndexRoute =
  AuthenticatedSectionsIndexRouteImport.update({
    id: '/sections/',
    path: '/sections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/account': typeof AuthenticatedAccountRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/comments/': typeof AuthenticatedCommentsIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/countries/': typeof AuthenticatedCountriesIndexRoute
  '/episodes/': typeof AuthenticatedEpisodesIndexRoute
  '/factors/': typeof AuthenticatedFactorsIndexRoute
  '/genres/': typeof AuthenticatedGenresIndexRoute
  '/header-menus/': typeof AuthenticatedHeaderMenusIndexRoute
  '/languages/': typeof AuthenticatedLanguagesIndexRoute
  '/movies/': typeof AuthenticatedMoviesIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/seasons/': typeof AuthenticatedSeasonsIndexRoute
  '/sections/': typeof AuthenticatedSectionsIndexRoute
  '/tags/': typeof AuthenticatedTagsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/account': typeof AuthenticatedAccountRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/comments': typeof AuthenticatedCommentsIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/episodes': typeof AuthenticatedEpisodesIndexRoute
  '/factors': typeof AuthenticatedFactorsIndexRoute
  '/genres': typeof AuthenticatedGenresIndexRoute
  '/header-menus': typeof AuthenticatedHeaderMenusIndexRoute
  '/languages': typeof AuthenticatedLanguagesIndexRoute
  '/movies': typeof AuthenticatedMoviesIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/seasons': typeof AuthenticatedSeasonsIndexRoute
  '/sections': typeof AuthenticatedSectionsIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/comments/': typeof AuthenticatedCommentsIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/countries/': typeof AuthenticatedCountriesIndexRoute
  '/_authenticated/episodes/': typeof AuthenticatedEpisodesIndexRoute
  '/_authenticated/factors/': typeof AuthenticatedFactorsIndexRoute
  '/_authenticated/genres/': typeof AuthenticatedGenresIndexRoute
  '/_authenticated/header-menus/': typeof AuthenticatedHeaderMenusIndexRoute
  '/_authenticated/languages/': typeof AuthenticatedLanguagesIndexRoute
  '/_authenticated/movies/': typeof AuthenticatedMoviesIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/seasons/': typeof AuthenticatedSeasonsIndexRoute
  '/_authenticated/sections/': typeof AuthenticatedSectionsIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/account'
    | '/errors/$error'
    | '/comments/'
    | '/contacts/'
    | '/countries/'
    | '/episodes/'
    | '/factors/'
    | '/genres/'
    | '/header-menus/'
    | '/languages/'
    | '/movies/'
    | '/roles/'
    | '/seasons/'
    | '/sections/'
    | '/tags/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/account'
    | '/'
    | '/errors/$error'
    | '/comments'
    | '/contacts'
    | '/countries'
    | '/episodes'
    | '/factors'
    | '/genres'
    | '/header-menus'
    | '/languages'
    | '/movies'
    | '/roles'
    | '/seasons'
    | '/sections'
    | '/tags'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/account'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/comments/'
    | '/_authenticated/contacts/'
    | '/_authenticated/countries/'
    | '/_authenticated/episodes/'
    | '/_authenticated/factors/'
    | '/_authenticated/genres/'
    | '/_authenticated/header-menus/'
    | '/_authenticated/languages/'
    | '/_authenticated/movies/'
    | '/_authenticated/roles/'
    | '/_authenticated/seasons/'
    | '/_authenticated/sections/'
    | '/_authenticated/tags/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comments/': {
      id: '/_authenticated/comments/'
      path: '/comments'
      fullPath: '/comments/'
      preLoaderRoute: typeof AuthenticatedCommentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/countries/': {
      id: '/_authenticated/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof AuthenticatedCountriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/episodes/': {
      id: '/_authenticated/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof AuthenticatedEpisodesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factors/': {
      id: '/_authenticated/factors/'
      path: '/factors'
      fullPath: '/factors/'
      preLoaderRoute: typeof AuthenticatedFactorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/genres/': {
      id: '/_authenticated/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof AuthenticatedGenresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/header-menus/': {
      id: '/_authenticated/header-menus/'
      path: '/header-menus'
      fullPath: '/header-menus/'
      preLoaderRoute: typeof AuthenticatedHeaderMenusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/languages/': {
      id: '/_authenticated/languages/'
      path: '/languages'
      fullPath: '/languages/'
      preLoaderRoute: typeof AuthenticatedLanguagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movies/': {
      id: '/_authenticated/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof AuthenticatedMoviesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons/': {
      id: '/_authenticated/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof AuthenticatedSeasonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sections/': {
      id: '/_authenticated/sections/'
      path: '/sections'
      fullPath: '/sections/'
      preLoaderRoute: typeof AuthenticatedSectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedCommentsIndexRoute: typeof AuthenticatedCommentsIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedCountriesIndexRoute: typeof AuthenticatedCountriesIndexRoute
  AuthenticatedEpisodesIndexRoute: typeof AuthenticatedEpisodesIndexRoute
  AuthenticatedFactorsIndexRoute: typeof AuthenticatedFactorsIndexRoute
  AuthenticatedGenresIndexRoute: typeof AuthenticatedGenresIndexRoute
  AuthenticatedHeaderMenusIndexRoute: typeof AuthenticatedHeaderMenusIndexRoute
  AuthenticatedLanguagesIndexRoute: typeof AuthenticatedLanguagesIndexRoute
  AuthenticatedMoviesIndexRoute: typeof AuthenticatedMoviesIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSeasonsIndexRoute: typeof AuthenticatedSeasonsIndexRoute
  AuthenticatedSectionsIndexRoute: typeof AuthenticatedSectionsIndexRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedCommentsIndexRoute: AuthenticatedCommentsIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedCountriesIndexRoute: AuthenticatedCountriesIndexRoute,
  AuthenticatedEpisodesIndexRoute: AuthenticatedEpisodesIndexRoute,
  AuthenticatedFactorsIndexRoute: AuthenticatedFactorsIndexRoute,
  AuthenticatedGenresIndexRoute: AuthenticatedGenresIndexRoute,
  AuthenticatedHeaderMenusIndexRoute: AuthenticatedHeaderMenusIndexRoute,
  AuthenticatedLanguagesIndexRoute: AuthenticatedLanguagesIndexRoute,
  AuthenticatedMoviesIndexRoute: AuthenticatedMoviesIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSeasonsIndexRoute: AuthenticatedSeasonsIndexRoute,
  AuthenticatedSectionsIndexRoute: AuthenticatedSectionsIndexRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
